apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: manav23/nodeserver
  newName: manav23/nodeserver
  newTag: 6300514f409ef4ca5a48d204a1148cca37883889
