apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: manav23/nodeserver
  newName: manav23/nodeserver
  newTag: 5394302e3bdb041c58ae661e2b235f3468417338
