apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: manav23/nodeserver
  newName: manav23/nodeserver
  newTag: 9a58c9cb142ac27f60723efd9583c7235aa09e31
